apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8081/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  ACCOUNTS_APPLICATION_NAME: accounts
  LOANS_APPLICATION_NAME: loans
  CARDS_APPLICATION_NAME: cards
  GATEWAY_APPLICATION_NAME: gatewayserver
