apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: loans
          image: mayank1783/cards:s15
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: CARDS_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: SPRING_CONFIG_IMPORT		
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE									

---
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
